title: xyz2bas
author: Sylvain PITIÉ
email: sylvain.pitie@u-paris.fr
description: Fortran code that convert xyz file to bas file for Fireball.
twitter_username: PitiéSylvain

theme: jekyll-theme-slate

